# The name of the workflow as it will appear in the Actions tab 
# of the GitHub repository.
name: build-web-site

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  lint:
    name: Lint Code Base
    # Set the agent to run on
    runs-on: ubuntu-latest
    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      ################################
      # Run Linter against code base #
      ################################
      - name: Lint Code Base
        uses: github/super-linter@v3
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: ${{ github.ref }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  build-site:
    #Name of the job
    name: Build github pages

    #Set the type of machine to run on
    runs-on: ubuntu-latest
    needs: lint
    env: 
        MARP_VERSION: 0.21.1
    steps:
       # Checks out a copy of your repository on the ubuntu-latest machine
       # https://github.com/actions/checkout
      - name: Checkout code
        uses: actions/checkout@v2 
        with:
            clean: true
            token: ${{ github.token }}

      # Runs the website build
      - run: sudo  wget -qO- https://github.com/marp-team/marp-cli/releases/download/v0.21.1/marp-cli-v$MARP_VERSION-linux.tar.gz | tar xvz
      - run: chmod +x marp && export PATH=$PATH:$(pwd) &&  mkdir site && marp slides/README.md -o site/index.html

      #https://github.com/marketplace/actions/deploy-to-github-pages
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with: # Set the secret as an input
          GITHUB_TOKEN: ${{ secrets.DEPLOYMENT_ACCESS_KEY }}
          BRANCH: gh_pages
          FOLDER: site


